2020-09-13 18:40:07,456 ERROR Exception on /add_groups [GET] [in %(lineno)d]
Traceback (most recent call last):
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/kukri/Janus/app/routes.py", line 148, in add_groups
    return render_template('select_groups.html', title='Lisää ryhmiä', form=form)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/kukri/.local/lib/python3.6/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/kukri/.local/lib/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/kukri/.local/lib/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/kukri/.local/lib/python3.6/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: select_groups.html
2020-09-13 18:41:36,871 INFO Janus sartup [in %(lineno)d]
2020-09-13 18:42:43,633 INFO Janus sartup [in %(lineno)d]
2020-09-13 18:42:45,311 ERROR Exception on /add_groups [GET] [in %(lineno)d]
Traceback (most recent call last):
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/kukri/Janus/app/routes.py", line 148, in add_groups
    return render_template('add_groups.html', title='Lisää ryhmiä', form=form)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/kukri/.local/lib/python3.6/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/kukri/.local/lib/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/kukri/.local/lib/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/kukri/.local/lib/python3.6/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/home/kukri/.local/lib/python3.6/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/kukri/.local/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/kukri/.local/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/kukri/Janus/app/templates/add_groups.html", line 2, in template
    {% import 'bootstrap/wtf.html' ad wtf %}
jinja2.exceptions.TemplateSyntaxError: expected token 'as', got 'ad'
2020-09-13 18:43:06,285 INFO Janus sartup [in %(lineno)d]
2020-09-13 18:44:23,795 ERROR Exception on /add_groups [POST] [in %(lineno)d]
Traceback (most recent call last):
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/kukri/Janus/app/routes.py", line 145, in add_groups
    marking = Group(marking=form.marking.data)
NameError: name 'Group' is not defined
2020-09-13 18:44:48,510 INFO Janus sartup [in %(lineno)d]
2020-09-13 18:44:56,030 ERROR Exception on /add_groups [POST] [in %(lineno)d]
Traceback (most recent call last):
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/kukri/Janus/app/routes.py", line 147, in add_groups
    db.commit()
AttributeError: 'SQLAlchemy' object has no attribute 'commit'
2020-09-13 18:45:23,657 INFO Janus sartup [in %(lineno)d]
2020-09-13 18:51:55,943 INFO Janus sartup [in %(lineno)d]
2020-09-13 18:52:03,471 INFO Janus sartup [in %(lineno)d]
2020-09-13 18:52:43,108 INFO Janus sartup [in %(lineno)d]
2020-09-13 18:53:50,339 INFO Janus sartup [in %(lineno)d]
2020-09-13 18:54:03,874 INFO Janus sartup [in %(lineno)d]
2020-09-13 18:54:15,583 INFO Janus sartup [in %(lineno)d]
2020-09-13 18:54:21,586 INFO Janus sartup [in %(lineno)d]
2020-09-13 18:54:32,039 INFO Janus sartup [in %(lineno)d]
2020-09-13 18:55:19,602 INFO Janus sartup [in %(lineno)d]
2020-09-13 19:03:23,571 INFO Janus sartup [in %(lineno)d]
2020-09-13 19:03:57,404 ERROR Exception on /attendance/group_select [GET] [in %(lineno)d]
Traceback (most recent call last):
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/kukri/Janus/app/routes.py", line 170, in group_select
    groups_query = Group.query.all()
NameError: name 'Group' is not defined
2020-09-13 19:04:20,784 INFO Janus sartup [in %(lineno)d]
